### ISSUE TITLE
Connecting to Streamer issue

### ISSUE THREAD

**Issue by msuch** [Microsoft/HoloLensForCV#13]
Hello there,

I have a problem when running Streamer app on HL and trying to connect to it through ComputeOnDesktop.

Streamer on HL works fine - I can air-tap and I see updated video stream object. Launching ComputeOnDesktop, after entering IP app waits 30 seconds then throws an exception:
`WinRT information: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

IP address is correct (app is deployed wirelessly). I checked nmap on HL device for open ports while Streamer is running, but only http/s were open (I was expecting 23940 to be also open).

**Comment by mtee** [comment]
having the exactly same issue as @msuch. Perhaps you were able to find a workaround in the meantime?

**Comment by msuch** [comment]
@mtee that worked, thank you!

**Comment by leonardo-menjivar** [comment]
To target an App on the HoloLens for ComputeOnDesktop, which IP should I enter when asked for it? It is a dedicated App on the HL (not deployed wirelessly). Should I deploy the app wirelessly and then deploy the ComputeOnDesktop?

**Comment by valavakilian** [comment]
I have the same problem as leonardo-menjivar when deploying with a usb cable

**Comment by leonardo-menjivar** [comment]
Hello @valavakilian I haven't been able to solve this so far.

**Comment by argo422** [comment]
Same issue encountered with ComputeOnDesktop. Receiver runs for ~20 seconds and then throws the same exception. Disabling 'Require SSL' had no impact.
