### ISSUE TITLE
Can I use this in Unity

### ISSUE THREAD

**Issue by A00107408** [microsoft/HoloLensForCV#143]
I am developing an app for the HoloLens 2 to augment the solution of a real world Rubik's Cube. I need access to the video feed as continuous frames to augment the real world Cube. Can I use this repo in Unity or how is it intended to be used?

I am porting my app from the META2 AR HMD where i was able to access the camera feed like a normal web camera and it all worked really well.

**Comment by dakesse** [comment]
You probably found these:
#51 and #108
