### ISSUE TITLE
ComputeOnDevice dll error

### ISSUE THREAD

**Issue by doughtmw** [Microsoft/HoloLensForCV#18]
Hey! I'm having some trouble running ComputeOnDevice. I keep getting an error with the `ucrtbased.dll` file when running on my device (and remoting). I'm able to run the Streamer and Receivers on my device with no issues. The error is below. Any help would be much appreciated! 

`Unhandled exception at 0x630F1FD5 (ucrtbased.dll) in ComputeOnDevice.exe: An invalid parameter was passed to a function that considers invalid parameters fatal. occurred`

**Comment by polszta** [comment]
This is tricky to diagnose correctly without having access to your setup... Do you think you could tweak your debugger's exception settings to enable first-chance exception handling for C++ and share more information about where in the code the error is triggered?

**Comment by polszta** [comment]
Also, see the discussion in issue #10 -- it's likely that you'll hit a few continuable exceptions before getting to the error that is actually blocking you.
