### ISSUE TITLE
Null frames in Streamer

### ISSUE THREAD

**Issue by doughtmw** [Microsoft/HoloLensForCV#24]
## Overview
Testing the ```Streamer``` function for accessing Research Mode streams (on RS4 with Research Mode enabled) I am getting errors for null frames in the Visible Light Left/Right Front and Short Throw ToF Depth (but not the Short Throw ToF Reflectivity) data streams. The sensors are recognized and initialized properly, but then when the stream begins I get a bunch of errors for null frames.

```cpp
MediaFrameSourceGroup::GetSensorType:: found sensor name 'Short Throw ToF Depth' in MF_MT_USER_DATA (blob has 44 bytes)
MediaFrameSourceGroup::GetSubtypeForFrameReader: evaluating MediaFrameSourceKind::Depth with format Video-D16 @15/1Hz
MediaFrameSourceGroup::InitializeMediaSourceWorkerAsync: created the 'ShortThrowToFDepth' frame reader
The thread 0xda4 has exited with code 0 (0x0).

MediaFrameReaderContext::FrameArrived: _sensorType=ShortThrowToFDepth (1), frame is null
```
Attached is a screenshot of the data stream when running ```Streamer```.
![20180517_151858_hololens](https://user-images.githubusercontent.com/25186390/40198996-1b5e5372-59e6-11e8-87db-efd81e9246f4.jpg)

## Steps to reproduce
Running ```Streamer``` from Master branch with default settings. 

RS4 Update 6 - Build 17134.1011 - Research Mode enabled
VS 2017 Community - V 15.7.1

**Comment by FracturedShader** [comment]
Null frames can happen. The output rate of the hardware won't necessarily match the capture rate. I wouldn't worry about it.
