### ISSUE TITLE
Cannot connect to streamer app running on HL 

### ISSUE THREAD

**Issue by DWatkins** [Microsoft/HoloLensForCV#30]
When I try running ComputeOnDesktop on my local machine, I receive the following exception:

```
Exception thrown at 0x74F2D722 in ComputeOnDesktop.exe: Microsoft C++ exception: Platform::COMException ^ at memory location 0x1366F4C0. HRESULT:0x8007274C A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
WinRT information: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

I have the correct IP address of the HL entered, and I am letting it connect to the default 23940 PV camera service name

**Comment by polszta** [comment]
Could you please try the workaround suggested in issue #13?

**Comment by DWatkins** [comment]
That workaround didn't work.

As a bit more information, I could not build the solutions when directly cloning the repo, I had to download the zip file in the readme. Trying to build directly from master just threw errors about not being able to find `pch.h`

Also, when running the streamer app, the video feed on the HL is rotated 90 degrees.

I don't know how relevant any  of that is to this issue though.  nmap on the HL's ip does not show port 23940 open, even after unchecking the SSL connection box in settings.

![image](https://user-images.githubusercontent.com/455381/41539754-378dff3c-72d4-11e8-99d7-8ad52607352c.png)

**Comment by cdorin** [comment]
I'm having the same issue and I also don't see port 23940 open after unchecking SSL connection.
Is there any other way to solve this?

**Comment by leonardo-menjivar** [comment]
I am having the same problem. I tried the workaround but the problems persists.

**Comment by leonardo-menjivar** [comment]
@cdorin how do you check for the open ports?

**Comment by polszta** [comment]
The streamer app defaulted to sending the VLC images, and that was not compatible with some of the older samples. I have just forked the tools, with one fork handling the PV camera (compatible with ComputeOnDesktop) and another fork specialized for the VLCs. Can you give the new version of the tools a try (StreamerVLC + ReceiverVLC, StreamerPV + ReceiverPV, or StreamerPV + ComputeOnDesktop)?

**Comment by DWatkins** [comment]
That worked!  Thanks!

**Comment by valavakilian** [comment]
I installed streamerPV on the Hololens and I run it while running the ComputeOnDesktop on the device. The Hololens and my PC are connected via a USB cable. I'm not sure how to connect it with the correct IP and port to use the Depth and PhotoVideo but I know the correct ports from the file  : Shared/HoloLensForCV/SensorFrameStreamer.cpp
But I still get the exception that the Host is either not recognized or does not allow the connection. However I disabled SSL for the Hololens. Can someone please help me with that ?
Thank you
