### ISSUE TITLE
FrameRenderer hard-codes depth range to 0.2f to 1.0f ?

### ISSUE THREAD

**Issue by mtaulty** [Microsoft/HoloLensForCV#34]
While running the StreamViewer sample on my HoloLens, I noticed that the 'far' depth stream didn't seem to be displaying anything other than nearby artefacts and this turned out to be because (AFAICT) FrameRenderer.cpp hard-codes the acceptable depth range to 0.2m to 1.0m whereas it seems like the 'long range' depth stream works beyond about the 0.8m range? I reworked mine to 0.2m to 4.0m and got better results for that stream so wondering why the sample doesn't allow that range and/or why it doesn't use the range values from the APIs themselves?

**Comment by polszta** [comment]
I think have fixed this yesterday -- could you please give the latest a try?

Also, I'm not sure we're populating these ranges properly in the API just yet -- could you please file a product bug through Feedback Hub?

**Comment by mtaulty** [comment]
Great, thanks - yes, see the change and understand not using the API for the values if it's not reporting them correctly (or at all!).
