### ISSUE TITLE
ComputeOnDevice

### ISSUE THREAD

**Issue by holoLens8** [Microsoft/HoloLensForCV#44]
I saw that you are using the Canny edge detector, is there a possibility to use another detector? \
Thanks in advance

**Comment by polszta** [comment]
Yes. The purpose of the sample is to show how to use OpenCV with the image streams. It should be possible to use any other OpenCV functionality, or follow the OpenCV integration to make some other CV libraries work.

**Comment by holoLens8** [comment]
Thank you
