### ISSUE TITLE
Streamer : ShortThrowToFDepth

### ISSUE THREAD

**Issue by Giminaan** [Microsoft/HoloLensForCV#47]
Hi, I'm trying to send HoloLens **ShortThrowToFDepth** data through the **Streamer** project and receive it with the **Receiver** on the desktop.

[Here is what I've been trying to do so far](https://stackoverflow.com/questions/51417096/how-to-get-hololens-shortthrowtofdepth-stream-using-streamer-receiver-projects), but I think this is wrong.

Would there be anyone who can help with this issue?

Thank you.

**Comment by polszta** [comment]
I have just pushed some changes that split the Receiver and Streamer tools into two versions, one handling the photo/video camera, and one handling the new research mode sensors (specifically, the 4 visible light cameras). Enabling the latter required fixing a bug in the receiver that was not unpacking the frames correctly. I haven't tried streaming depth and reflectivity yet, but there's a good chance it should work with some amount of tweaking.

The specific issue you are hitting seems to be something else, and it looks like you're on the right track -- XAML only allows Bgra8 images, so you need to convert the Gray16 stream to Bgra8. There is some code in the streamer that should do it (look for TransformBitmap).

**Comment by Giminaan** [comment]
It works!. Thank you for your help!
