### ISSUE TITLE
The recorder_console.py results in error

### ISSUE THREAD

**Issue by ahmadyan** [Microsoft/HoloLensForCV#50]
Hi,
I have deployed the CV recorder app on Hololens. It is recording just fine and I can see the files in File Explorer. 

However, when I try to use the recorder_console script to download/construct/view/... the files, it rans into the following problem:

```
Searching for recordings...
Traceback (most recent call last):
  File "recorder_console.py", line 667, in <module>
    main()
  File "recorder_console.py", line 602, in main
    args.dev_portal_password)
  File "recorder_console.py", line 116, in connect
    self.url, self.package_full_name))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File 
....
"/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

I traced back the error (the url address is `http://172.22.61.5/api/filesystem/apps/files?knownfolderid=LocalAppData&packagefullname=7A37D94C-C432-4875-8C57-FA185E1C92B4_1.0.0.0_x86__1e2jkdcqpv8b4&path=\\TempState`) and the returned result is 

`{"Code" : -2135228013, "CodeText" : "Unavailable", "Reason" : "Unsupported known folder id", "Success" : false}`

@ahojnnes

**Comment by ahojnnes** [comment]
How did you connect the HoloLens to the computer? I assume not through the USB cable, since I see a different IP address?

**Comment by ahmadyan** [comment]
Through wifi. 

The issue was related to SSL certificate. I disabled the SSL on Hololens and it went away. I will close this issue.

**Comment by cyrineee** [comment]
@ahmadyan  how did u fix that ? i have the same error

**Comment by cyrineee** [comment]
i get this error 

![error](https://user-images.githubusercontent.com/42346254/56803144-30e4f980-6822-11e9-9a68-364a4d76f135.PNG)
