### ISSUE TITLE
HoloLensForCV.winmd could not be found

### ISSUE THREAD

**Issue by turowicz** [microsoft/HoloLensForCV#58]
Hey guys,

I'm new to this, so please forgive me if the below is a rookie error. I've installed VS17 and required HoloLens tools (https://docs.microsoft.com/en-us/windows/mixed-reality/install-the-tools#installation-checklist-for-hololens).

Unfortunately I can't build the project and I get the following:

```
1>------ Build started: Project: Debugging, Configuration: Debug Win32 ------
1>Object reference not set to an instance of an object.
2>------ Build started: Project: Io, Configuration: Debug Win32 ------
2>Object reference not set to an instance of an object.
3>------ Build started: Project: Audio, Configuration: Debug Win32 ------
3>Object reference not set to an instance of an object.
4>------ Build started: Project: Rendering, Configuration: Debug Win32 ------
4>Object reference not set to an instance of an object.
5>------ Build started: Project: SensorStreamViewer, Configuration: Debug Win32 ------
5>Object reference not set to an instance of an object.
6>------ Build started: Project: Graphics, Configuration: Debug Win32 ------
6>Object reference not set to an instance of an object.
7>------ Build started: Project: HoloLensForCV, Configuration: Debug Win32 ------
7>Object reference not set to an instance of an object.
8>------ Build started: Project: BatchProcessing, Configuration: Debug Win32 ------
8>Object reference not set to an instance of an object.
9>------ Build started: Project: OpenCVHelpers, Configuration: Debug Win32 ------
9>Object reference not set to an instance of an object.
10>------ Build started: Project: Holographic, Configuration: Debug Win32 ------
11>------ Build started: Project: ReceiverPV, Configuration: Debug x86 ------
12>------ Build started: Project: ReceiverVLC, Configuration: Debug x86 ------
10>Object reference not set to an instance of an object.
13>------ Build started: Project: ComputeOnDesktop, Configuration: Debug Win32 ------
13>Object reference not set to an instance of an object.
14>------ Build started: Project: ComputeOnDevice, Configuration: Debug Win32 ------
14>Object reference not set to an instance of an object.
15>------ Build started: Project: StreamerPV, Configuration: Debug Win32 ------
15>Object reference not set to an instance of an object.
16>------ Build started: Project: StreamerVLC, Configuration: Debug Win32 ------
16>Object reference not set to an instance of an object.
17>------ Build started: Project: Recorder, Configuration: Debug Win32 ------
17>Object reference not set to an instance of an object.
18>------ Build started: Project: ArUcoMarkerTracker, Configuration: Debug Win32 ------
18>Object reference not set to an instance of an object.
11>C:\Users\wojci\Workspace\HoloLensForCV\Tools\ReceiverPV\ReceiverPV.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'C:\Users\wojci\Workspace\HoloLensForCV\Debug\HoloLensForCV\HoloLensForCV.winmd'
11>CSC : error CS0006: Metadata file 'C:\Users\wojci\Workspace\HoloLensForCV\Debug\HoloLensForCV\HoloLensForCV.winmd' could not be found
12>C:\Users\wojci\Workspace\HoloLensForCV\Tools\ReceiverVLC\ReceiverVLC.csproj : XamlCompiler error WMC1006: Cannot resolve Assembly or Windows Metadata file 'C:\Users\wojci\Workspace\HoloLensForCV\Debug\HoloLensForCV\HoloLensForCV.winmd'
12>CSC : error CS0006: Metadata file 'C:\Users\wojci\Workspace\HoloLensForCV\Debug\HoloLensForCV\HoloLensForCV.winmd' could not be found
========== Build: 0 succeeded, 18 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by turowicz** [comment]
I was also forced to create a symlink between `Shared\Io\Shared` and `Shared\Debugging`

**Comment by turowicz** [comment]
paging @polszta

**Comment by pranaabdhawan** [comment]
I am getting the same error message

**Comment by luljetasinani** [comment]
Anyone a suggestion on how to proceed?

**Comment by xiaoxiaowenge** [comment]
Anyone can tell me how fix

**Comment by hygxy** [comment]
Any updates? I have the same issue

**Comment by yugen12** [comment]
Anyone please?

**Comment by kaiwu119** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2220	the following warning is treated as an error	HoloLensForCV	X:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\xstring	2390	
Warning	C4244	'argument': conversion from '_Elem' to 'const _Elem', possible loss of data	HoloLensForCV	X:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\xstring	2390	
Error	MSB4181	The "CompileXaml" task returned false but did not log an error.	HoloLensForCV	X:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets	486	
Error	C1192	#using failed on 'M:\ARProject\HoloLensForCV-master\Release\HoloLensForCV\HoloLensForCV.winmd'	OpenCVHelpers	M:\ARProject\HoloLensForCV-master\Shared\OpenCVHelpers\pch.cpp	1	
Error	MSB4181	The "CompileXaml" task returned false but did not log an error.	OpenCVHelpers	X:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets	486	
Error	C1192	#using failed on 'M:\ARProject\HoloLensForCV-master\Release\HoloLensForCV\HoloLensForCV.winmd'	Holographic	M:\ARProject\HoloLensForCV-master\Shared\Holographic\pch.cpp	1	
Error	MSB4181	The "CompileXaml" task returned false but did not log an error.	Holographic	X:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets	486	
Error	C1192	#using failed on 'M:\ARProject\HoloLensForCV-master\Release\HoloLensForCV\HoloLensForCV.winmd'	ComputeOnDevice	M:\ARProject\HoloLensForCV-master\Samples\ComputeOnDevice\pch.cpp	1	
Error	MSB4181	The "CompileXaml" task returned false but did not log an error.	ComputeOnDevice	X:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets	486	

above are my errors!
I use vs2019 to run this project, who can help me

**Comment by Joon-Jung** [comment]
Go to project properties of HoloLensForCV -> C/C++ -> General and change **Treat warnings as errors** from "Yes (/WX)" to "No (/WX-)".

**Comment by USTBVEO** [comment]
the same question Anyone please?
