### ISSUE TITLE
What does ^ mean when used in declaration of a name?

### ISSUE THREAD

**Issue by JoyXu123** [Microsoft/HoloLensForCV#59]
In the sample codes, there are a lot of instances declared with ^ at the end, for example, 

virtual Windows::ApplicationModel::Core::IFrameworkView^ CreateView();

What does ^ mean or use in this case?

**Comment by ahojnnes** [comment]
This is a language feature of CX/C++, see https://blogs.msdn.microsoft.com/vcblog/2012/09/17/ccx-part-2-of-n-types-that-wear-hats/ for more details.
