### ISSUE TITLE
Simultaneous remote rendering and camera access

### ISSUE THREAD

**Issue by LDeakin** [Microsoft/HoloLensForCV#6]
I have previously brought up this issue [here](https://github.com/Microsoft/MixedRealityCompanionKit/issues/104) in April.

For the AR application I am trying to make, I need to simultaneously remotely render and access the camera stream. I can remotely render with [this](https://github.com/Microsoft/MixedRealityCompanionKit/tree/master/RemotingHostSample) and access the camera stream with [this](https://github.com/Microsoft/MixedRealityCompanionKit/tree/master/MixedRemoteViewCompositor) or this current repository. Unfortunately, I can't remotely render and access the camera stream simultaneously because the functionality is provided by separate apps on the HoloLens side.

I would like to merge the functionality into a single app, but I have not been able to reproduce the functionality of the closed-source  *Holographic Remoting Player* app. I don't know who to contact about this, so I am requesting it again here. It would be nice to have the *Holographic Remoting Player* app open sourced  - or at least a minimal example provided - so I can mix it in with the streamer in this repository.

**Comment by sshiv** [comment]
LDeakin,
Thanks for opening this issue. We do not own the Holographic Remoting Player application. I am presuming that you have already opened an issue at their GitHub repository. 

However If I may suggest a workaround. You could modify the Streamer application at our repository to do local rendering and streaming at the same time and check if Remote renderer can be modified to access this stream. 

Thanks

**Comment by LDeakin** [comment]
Hi @sshiv ,

Thanks for the response. Your workaround would work but I need to be able to remotely render due to the complexity of what I am rendering.

Could you put me in contact with someone who owns the Holographic Remoting Player application? There appears to be no public GitHub repository for this app.
