### ISSUE TITLE
Project "Recorder" doesn't capture the Photo/Video  image. 

### ISSUE THREAD

**Issue by AlexSyx** [Microsoft/HoloLensForCV#60]
I ran the project "Recorder" and got many files such as long_throw_depth.tar,etc
However ,the file pv.tar turned out to be empty. 
How should i get pv images which has One-to-one correspondence with depth image?

**Comment by ahojnnes** [comment]
You would have to change the source code of the recorder application. Currently the photo video camera is not recorded. See Recorder/AppMain.cpp at the very bottom. Let me know if anything else is unclear.

**Comment by AlexSyx** [comment]
Thanks,I managed to get the PV image by modifying the code in AppMain.cpp and SensorFrameRecorderSink.cpp as you said. However the PV Image has a quite different view from the depth image,which doesnt meet my need.So is there any way i can get a RGB image with match closely to the depth image?(ps:  I want to do some machine learning works using the RGB images and the correspond depth images).What about the reflectivity-image? I'm looking into it now.......

**Comment by ahojnnes** [comment]
The research mode gives you the sensor poses for both the PV camera and the depth sensor, so you could reproject the depth images to the PV image (including some occlusion handling).

**Comment by cxnvcarol** [comment]
I know it's a closed issue, and I have the last version of the master branch, but I still can't manage to get the PV image together with the rest of the streams in the recorder app. It seems that only one MediaFrameSourceGroup is detected which is "sensor streaming" and has only 8 sensor streams (4 gray, 2 Tof x depth & reflectivity). I've also the PV sensor type in the MediaFrameSourceGroup.CPP for the hololensresearchmodesensors but still no luck. What am I missing? thank you!
