### ISSUE TITLE
README is out of date at Shared/HoloLensForCV?

### ISSUE THREAD

**Issue by nmsmith** [Microsoft/HoloLensForCV#65]
The README at [this](https://github.com/Microsoft/HoloLensForCV/tree/master/Shared/HoloLensForCV) location says:

> Note that support for additional HoloLens sensors (ToF Depth, Visible Light, ...) is not currently available publicly. Stay tuned for updates!

I'm assuming these sensors are now exposed, and the README needs an update?

**Comment by ahojnnes** [comment]
Right, thanks. This is fixed now.
