### ISSUE TITLE
Tools/Recorder No Longer Working on OS Build 10.0.17763.134

### ISSUE THREAD

**Issue by gopikaajaykumar** [Microsoft/HoloLensForCV#66]
After the HoloLens was updated to an OS build of 10.0.17763.134, the Recorder tool, which worked fine previously, is no longer working. Specifically, when I air tap to stop recording, the "Ending recording, wait a moment to finish" message is skipped and instead the message "Finished recording" is played. The archives are also corrupted and the csv's are empty.

**Comment by Huangying-Zhan** [comment]
Having the same issue.
Recorder program works well on HoloLens RS4 build (17143).
However, the device automatically updated to RS5 build (17763.134) and the Recorder program doesn't work on it.
It still creates the files (.tar, .csv) but nothing is recorded.
Here is the part of the debug output
```
MediaFrameSourceGroup::GetSensorType:: assuming SensorType::Undefined given missing MF_MT_USER_DATA
MediaFrameSourceGroup::InitializeMediaSourceWorkerAsync: could not map the media frame source to a Research Mode sensor type!
MediaFrameSourceGroup::InitializeMediaSourceWorkerAsync: no eligible sources in 'MN34150'
```

**Comment by gopikaajaykumar** [comment]
I have the same debug output as @Huangying-Zhan too.

**Comment by gopikaajaykumar** [comment]
Not sure if this is related, but I'm also unable to receive sensor data on the ReceiverVLC project. I am able to connect successfully to the Hololens server, which runs StreamerVLC, but after that it looks like I get stuck in the ReceiveAsync function and don't receive any sensorFrame images. I thought I'd mention this in case this problem is related to why the Recorder is no longer working, but I may also just be running the Receiver or Streamer project incorrectly (I hadn't attempted to run the Streamer/Receiver pair on the RS4 build since I was only using the Recorder so this was my first attempt in running them.) Mostly tried it out now to see if there's some systemic issue with the Research Mode sensors on the latest build

**Comment by polszta** [comment]
The issue with recorder should now be fixed with pull request #68.  @Huangying-Zhan, could you please give this a quick try?

@gopikaajaykumar could you please file a separate issue for this?

**Comment by gopikaajaykumar** [comment]
Will do

**Comment by Huangying-Zhan** [comment]
@polszta , unfortunately, I don't have a device for testing at the moment. 

Hi, @gopikaajaykumar Could you give a try?

**Comment by gopikaajaykumar** [comment]
@Huangying-Zhan Sure, I'll give it a try tomorrow and post an update here. Thanks

**Comment by gopikaajaykumar** [comment]
@polszta @Huangying-Zhan The Tools/Recorder project is now working after pull request #68. Thanks for the fix and the help
