### ISSUE TITLE
Unable to receive sensor data on the ReceiverVLC project

### ISSUE THREAD

**Issue by gopikaajaykumar** [microsoft/HoloLensForCV#69]
I am unable to receive sensor data on the ReceiverVLC project. I am able to connect successfully to the Hololens server, which runs StreamerVLC, but after that it looks like I get stuck in the ReceiveAsync function and don't receive any sensorFrame images. I may also just be running the Receiver or Streamer project incorrectly (I hadn't attempted to run the Streamer/Receiver pair on the RS4 build since I was only using the Recorder so this was my first attempt in running them.) Mostly tried it out now to see if there's some systemic issue with the Research Mode sensors on the latest build

**Comment by fbogo** [comment]
Are you connecting via wifi (with both PC and HoloLens connected to the same network)?
It works fine for me, after inserting the HoloLens IP address in the ReceiverVLC.

**Comment by gopikaajaykumar** [comment]
Yes I am. I have not tried the project after the latest commit, however. It may be working now. I will check and give an update.

**Comment by cyrineee** [comment]
should i run the streamer VLC and the recieverVLC at the same time in different windows to have the data stored ?

**Comment by felixvh** [comment]
Well, I assume the streamer should be running on HoloLens and then you start the receiver on your computer.

**Comment by cyrineee** [comment]
Niiice it works for me thanks.
but where can i get the data from sensors and the images ?
________________________________
